version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: hseeberger/scala-sbt:11.0.4_1.3.2_2.12.10
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.1.4
        environment:
            discovery.type: "single-node"
            cluster.name:  "elasticsearch"
      - image: quay.io/keycloak/keycloak:13.0.1
        environment:
            KEYCLOAK_USER: "admin"
            KEYCLOAK_PASSWORD: "admin"
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: sbt-cache
      - run:
          name: Run tests
          command: cat /dev/null | sbt clean test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - store_test_results:
          path: target/test-reports
